### ISSUE TITLE
Capitals in matrix IDs

### ISSUE THREAD

**Issue by mfasi** [mmikaitis/anymatrix#2]
Anymatrix doesn't seem to support capitals in matrix IDs. **Reason** the `command` is converted to lower case here

https://github.com/mmikaitis/anymatrix/blob/6c5e97653c4640783d3e4dd7cd804e07f8117050/anymatrix.m#L185

thus all entries in `matrix_IDs` must be lower-case. But this is not consistent with the check

https://github.com/mmikaitis/anymatrix/blob/6c5e97653c4640783d3e4dd7cd804e07f8117050/anymatrix.m#L189

**Comment by mmikaitis** [comment]
Good spot, many thanks for the fix.
