### ISSUE TITLE
Matrices are ignored if group or matrix ID contain uppercase characters

### ISSUE THREAD

**Issue by mfasi** [mmikaitis/anymatrix#8]
The string normalizations
https://github.com/mmikaitis/anymatrix/blob/70886ee31a36053846aafafa186c367cbaae1351/anymatrix.m#L181
https://github.com/mmikaitis/anymatrix/blob/70886ee31a36053846aafafa186c367cbaae1351/anymatrix.m#L185
eems to cause issues with
```
anymatrix('scan')
```
as groups and matrices containing capitals are ignored.

**Comment by mmikaitis** [comment]
These lines only remove capitalization in the arguments and commands to anymatrix, so it should not impact the scanning of the filesystem with anymatrix('scan'). I tried to change core/hesfull01 to core/Hesfull01 and it seems to work (scan finds the new matrix with a capital 'H'). Could you give an example of the problem you are facing with scan? The issue could be somewhere in the scanning functions, starting at line 294. Many thanks.

**Comment by mfasi** [comment]
Yes, the scan would probably work, but then I think you'd then get an error if you tried to generate the matrix with
```
anymatrix('core/Hessful01')
```

Something similar should happen if you changed `core` to `Core`.

**Comment by mmikaitis** [comment]
Yes, that seems to be a problem. Looking at the user manual, only properties are case-insensitive, while matrix and group names are case sensitive. Fix merged. Many thanks.

**Comment by mfasi** [comment]
Great, thanks!
